name: edunova_app
description: A mobile application for curated learning resources supporting SDG 4 and SDG 17
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  crypto: ^3.0.7
  bcrypt: ^1.1.3
  
  # File handling
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  path: ^1.9.0
  
  # File viewing
  open_file: ^3.3.2
  
  # MIME type detection
  mime: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Uncomment the following line to add assets
  assets:
     - assets/images/

  # Uncomment the following lines to add custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700